import assert from 'node:assert/strict';
import {launchBrowser,startServer,openRoom,startSingle,backToLobby,watchErrors} from './lib/harness.mjs';
const server=await startServer({log:true});const browser=await launchBrowser();
const page=await browser.newPage({viewport:{width:390,height:844}});const errors=watchErrors(page);
const pointer=(selector,type,id)=>page.dispatchEvent(selector,type,{pointerId:id,pointerType:'touch',button:0,bubbles:true,cancelable:true});
const pressed=selector=>page.locator(selector).evaluate(el=>el.classList.contains('is-pressed'));
const prepare=async game=>{await startSingle(page,game);await page.waitForSelector('#minigame-intro',{state:'hidden'});};
try {
 await openRoom(page,server.base,{name:'Druckgefühl'});
 await pointer('#open-invite','pointerdown',11);
 assert.equal(await pressed('#open-invite'),true,'Druck erscheint sofort');
 await pointer('#open-invite','pointerdown',22);
 await pointer('body','pointerup',22);
 assert.equal(await pressed('#open-invite'),true,'Zweiter Finger löst den ersten nicht');
 await pointer('body','pointercancel',11);
 assert.equal(await pressed('#open-invite'),false,'Abbruch räumt sofort auf');
 console.log('✓ Menü: sofortiger Druck, zwei Finger, Abbruch');
 await prepare('ballonPump');
 await page.focus('[data-pump]');
 const before=await page.evaluate(()=>window.__tumblekinScene.localPumps);
 await page.keyboard.down('Space');await page.keyboard.down('Space');await page.keyboard.up('Space');
 assert.equal(await page.evaluate(()=>window.__tumblekinScene.localPumps),before+1,'Tastaturdruck ist genau eine Aktion, kein Repeat und kein doppeltes Ereignis');
 await page.waitForTimeout(150);
 assert.equal(await pressed('[data-pump]'),false);
 await page.locator('[data-pump]').evaluate(button=>button.click());
 assert.equal(await page.evaluate(()=>window.__tumblekinScene.localPumps),before+2,'Assistive click aktiviert die Spielaktion');
 await page.keyboard.down('Enter');await page.keyboard.down('Enter');await page.keyboard.up('Enter');
 assert.equal(await page.evaluate(()=>window.__tumblekinScene.localPumps),before+3,'Enter-Wiederholung darf keinen zweiten nativen click erzeugen');
 await page.waitForTimeout(150);
 const stagePressed=await page.evaluate(()=>{document.querySelector('canvas.kinetic-webgl').dispatchEvent(new PointerEvent('pointerdown',{pointerId:33,pointerType:'touch',button:0,bubbles:true,cancelable:true}));return document.querySelector('[data-pump]').classList.contains('is-pressed');});
 assert.equal(stagePressed,true,'Tippen auf die Bühne drückt denselben Knopf');
 await pointer('body','pointerup',33);
 await page.waitForTimeout(160);
 await pointer('[data-pump]','pointerdown',44);
 await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
 assert.equal(await pressed('[data-pump]'),false,'Fensterwechsel beendet den Druck');
 await page.emulateMedia({reducedMotion:'reduce'});
 await pointer('[data-pump]','pointerdown',45);
 assert.equal(await page.locator('[data-pump]').evaluate(el=>getComputedStyle(el).transform),'none','Reduzierte Bewegung verwendet den Schatten ohne Verschiebung');
 await pointer('body','pointercancel',45);
 await page.emulateMedia({reducedMotion:'no-preference'});
 console.log('✓ Pumpen: Tastatur, assistive Aktivierung, Bühne, Fensterwechsel, reduzierte Bewegung');
 // Die Fehlermeldung durchläuft das echte Netzwerk und den normalen Spieleingang.
 await page.waitForTimeout(200);
 const error=await page.evaluate(async()=>{try{await window.__tumblekinScene.sendInput({action:'unbekannt'});}catch(error){return error.message;}});
 assert.ok(error);assert.equal(await page.locator('#toast').textContent(),error);
 console.log('✓ Serverfehler wird sichtbar und nicht still geschluckt');
 await backToLobby(page);await prepare('lichtwaechter');
 await page.focus('[data-hold-run]');await page.keyboard.down('Space');
 await page.waitForFunction(()=>window.__tumblekinScene.holding);
 await page.keyboard.up('Space');await page.waitForFunction(()=>!window.__tumblekinScene.holding);
 await page.keyboard.down('Enter');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
 await page.waitForFunction(()=>!window.__tumblekinScene.holding);
 await page.keyboard.up('Enter');
 console.log('✓ Halteknopf: echte Tastaturhaltung, Loslassen und Unterbrechung');
 await backToLobby(page);await prepare('leuchtfolge');
 await page.waitForSelector('[data-memory-pad]:not(:disabled)');
 const sequence=await page.evaluate(()=>{const s=window.__tumblekinScene;const sequence=[...s.activeRound().round.sequence];for(const index of sequence)document.querySelector(`[data-memory-pad="${index}"]`).click();return sequence;});
 await page.waitForFunction(()=>document.querySelectorAll('[data-memory-pad]:disabled').length===4);
 assert.equal(await page.evaluate(()=>window.__tumblekinScene.local.count),sequence.length);
 await page.waitForFunction(()=>{const s=window.__tumblekinScene;return s.update.arcade.players[s.getControlledPlayerId()].survived>0;});
 console.log('✓ Leuchtfolge: Farbknöpfe spielen die echte Folge, Abschluss sperrt weitere Tipps');
 await backToLobby(page);await prepare('kanonenflug');
 assert.equal((await page.locator('[data-cannon-launch]').textContent()).trim(), 'KRAFT STOPPEN');
 await pointer('[data-cannon-launch]','pointerdown',77);await pointer('body','pointerup',77);
 await page.waitForFunction(()=>document.querySelector('[data-cannon-launch]').textContent.includes('WINKEL STOPPEN'));
 console.log('✓ Kanonenflug: Knopf erklärt Kraft und Winkel getrennt');
 await backToLobby(page);await prepare('schneeball');
 await page.waitForFunction(()=>!document.querySelector('[data-snow-dash]').disabled);
 assert.match(await page.locator('[data-snow-dash] b').textContent(),/SCHWUNG/);
 await page.locator('[data-snow-dash]').dispatchEvent('pointerdown');
 await page.waitForFunction(()=>{const s=window.__tumblekinScene;return s.update.arcade.players[s.getControlledPlayerId()].dashes>0;});
 await page.waitForFunction(()=>document.querySelector('[data-snow-dash]').disabled && /LÄDT/.test(document.querySelector('[data-snow-dash] b').textContent));
 console.log('✓ Schneeball: SCHWUNG legt los und zeigt dann klar, dass er lädt');
 await backToLobby(page);
 assert.equal(await page.evaluate(()=>window.__tumblekin.ui.feedback.buttons.states.size),0,'Szenenabbau räumt die Druckzustände auf');
 assert.deepEqual(errors,[]);assert.deepEqual(server.errorOutput,[]);
} finally {await browser.close();server.stop();}
